import { createClient } from '@supabase/supabase-js';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!;const key=process.env.SUPABASE_SERVICE_ROLE_KEY!;
if(!url||!key) throw new Error('Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY');
const supabase=createClient(url,key);
async function upsertUser(email:string,role:string){const {data:{users}}=await supabase.auth.admin.listUsers();let u=users.find(x=>x.email===email);if(!u){const {data}=await supabase.auth.admin.createUser({email,password:'Password123!',email_confirm:true,user_metadata:{primary_role:role}});u=data.user!}await supabase.from('profiles').upsert({id:u.id,email,full_name:email.split('@')[0],primary_role:role,onboarding_completed:true});return u.id}
async function main(){for(const b of ['profile-photos','candidate-cvs','intro-videos','candidate-documents','organisation-logos','message-attachments']) await supabase.storage.createBucket(b,{public:false}).catch(()=>{});
const recruiterUser=await upsertUser('recruiter@teachabroad.test','recruiter');const schoolRecruiterUser=await upsertUser('school@teachabroad.test','recruiter');const agencyOwner=await upsertUser('agency@teachabroad.test','organisation_admin');const schoolOwner=await upsertUser('owner-school@teachabroad.test','organisation_admin');
const {data:orgs}=await supabase.from('organisations').upsert([{name:'Global Teach Recruitment',slug:'global-teach-recruitment',organisation_type:'recruitment_agency',verified_status:'verified',country:'China',city:'Chengdu',description:'Verified agency for China teaching roles.'},{name:'Chengdu Bright Future Kindergarten',slug:'chengdu-bright-future-kindergarten',organisation_type:'school',verified_status:'verified',country:'China',city:'Chengdu',description:'Direct employer kindergarten in Chengdu.'}],{onConflict:'slug'}).select();
const agency=orgs!.find(o=>o.slug==='global-teach-recruitment')!, school=orgs!.find(o=>o.slug.includes('kindergarten'))!;
await supabase.from('organisation_memberships').upsert([{organisation_id:agency.id,user_id:agencyOwner,role:'owner'},{organisation_id:agency.id,user_id:recruiterUser,role:'recruiter'},{organisation_id:school.id,user_id:schoolOwner,role:'owner'},{organisation_id:school.id,user_id:schoolRecruiterUser,role:'recruiter'}],{onConflict:'organisation_id,user_id'});
const {data:recs}=await supabase.from('recruiter_profiles').upsert([{user_id:recruiterUser,organisation_id:agency.id,recruiter_type:'agency_recruiter',display_name:'Maya Chen',title:'Senior ESL Recruiter'},{user_id:schoolRecruiterUser,organisation_id:school.id,recruiter_type:'school_recruiter',display_name:'Li Wei',title:'HR Manager'}],{onConflict:'user_id'}).select();
const candIds=[];for(const [email,name,status,pct] of [['ana@teachabroad.test','Ana Miller','actively_looking',92],['sam@teachabroad.test','Sam Taylor','open_to_offers',78],['lee@teachabroad.test','Lee Morgan','not_looking',85]] as any){const uid=await upsertUser(email,'candidate');const {data:c}=await supabase.from('candidate_profiles').upsert({user_id:uid,display_name:name,headline:'ESL teacher ready for Asia',current_country:'United Kingdom',current_city:'London',nationality:'British',has_bachelors_degree:true,has_tefl:pct>80,years_teaching_experience:2,teaching_experience_summary:'Classroom and online ESL experience.',preferred_countries:['China'],employment_search_status:status,profile_completion_percentage:pct,is_profile_complete:pct>=80,email_verified_snapshot:true},{onConflict:'user_id'}).select().single();candIds.push(c.id)}
const jobs=[['Kindergarten ESL Teacher - Chengdu','kindergarten-esl-teacher-chengdu',school.id,recs![1].id,'Chengdu',true],['Primary School English Teacher - Shenzhen','primary-school-english-teacher-shenzhen',agency.id,recs![0].id,'Shenzhen',false],['Training Centre ESL Teacher - Chongqing','training-centre-esl-teacher-chongqing',agency.id,recs![0].id,'Chongqing',false],['International School English Teacher - Shanghai','international-school-english-teacher-shanghai',agency.id,recs![0].id,'Shanghai',false]];
const {data:jobRows}=await supabase.from('jobs').upsert(jobs.map(([title,slug,org,rec,city,sponsored])=>({title,slug,organisation_id:org,posted_by_recruiter_id:rec,description:'A transparent teaching-abroad role with visa support, onboarding, and direct application management through TeachAbroad Hub.',country:'China',city,location_text:`${city}, China`,school_type:title.toString().split(' ')[0],status:'live',salary_min:18000,salary_max:26000,salary_currency:'CNY',salary_period:'monthly',visa_sponsorship:true,bachelors_required:true,tefl_required:true,transparency_score:88,verified_by_platform:true,sponsored})),{onConflict:'organisation_id,slug'}).select();
const statuses=['applied','viewed','whitelisted','rejected','hired'];for(let i=0;i<5;i++){const job=jobRows![i%jobRows!.length], cand=candIds[i%candIds.length];await supabase.from('applications').upsert({job_id:job.id,candidate_id:cand,recruiter_id:job.posted_by_recruiter_id,organisation_id:job.organisation_id,status:statuses[i],candidate_snapshot:{seed:true},candidate_message:'I am interested in this role.'},{onConflict:'job_id,candidate_id'}).select().single().then(async ({data})=>{if(data){await supabase.from('application_status_history').insert({application_id:data.id,new_status:statuses[i],note:'Seeded status'});if(['whitelisted','hired'].includes(statuses[i])) await supabase.from('conversations').upsert({application_id:data.id,candidate_id:cand,recruiter_id:job.posted_by_recruiter_id,organisation_id:job.organisation_id,status:'open',opened_at:new Date().toISOString()},{onConflict:'application_id'});}})}
await supabase.from('resources').upsert(['China Z Visa Checklist','TEFL Certificate Guide','How to Prepare an Intro Video','Avoiding Bad Recruiters','Teaching Kindergarten Abroad'].map((title,i)=>({title,slug:title.toLowerCase().replaceAll(' ','-'),excerpt:'Practical guidance for teaching abroad candidates.',content:'Detailed guide content placeholder.',category:['visas','tefl','interviews','scams_and_safety','teaching_tips'][i],country:i===0?'China':null,visibility:i===3?'candidates_only':'public',published:true})),{onConflict:'slug'});
await supabase.from('sponsored_placements').insert({organisation_id:school.id,job_id:jobRows![0].id,placement_type:'featured_job',label:'Sponsored featured job',starts_at:new Date().toISOString(),ends_at:new Date(Date.now()+86400000*30).toISOString(),budget:500,currency:'USD',status:'active'});
console.log('Seed complete. Demo password: Password123!')}
main();
